# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kskostyl <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 21:11:06 by kskostyl          #+#    #+#              #
#    Updated: 2018/11/06 21:11:26 by kskostyl         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCE = main.c

all:
	gcc -Wall -Wextra -Werror $(SOURCE) -o do-op

clean:
	/bin/rm -f do-op

fclean:
	/bin/rm -f do-op

re: fclean all
